export const loginClassNames = {
  account: 'login__account',
  action: 'login__action',
  field: 'login__field',
  error: 'login__error',
  form: 'login__form',
  formTitle: 'login__form-title',
  menu: 'login__menu',
  panel: 'login__panel',
  passwordHint: 'login__password-hint',
  primary: 'login__primary',
  role: 'login__role',
  roleGrid: 'login__role-grid',
  roleSelected: 'login__role--selected',
  roles: 'login__roles',
  root: 'login',
  switch: 'login__switch',
} as const;
