export const FILE_FAILURE_CODES = {
  ANTIVIRUS_UNAVAILABLE: 'ANTIVIRUS_UNAVAILABLE',
  CLAMAV_INVALID_RESPONSE: 'CLAMAV_INVALID_RESPONSE',
  CLAMAV_UNAVAILABLE: 'CLAMAV_UNAVAILABLE',
  CONTENT_UNAVAILABLE: 'CONTENT_UNAVAILABLE',
  DECLARED_SIZE_MISMATCH: 'DECLARED_SIZE_MISMATCH',
  FILE_NOT_AVAILABLE: 'FILE_NOT_AVAILABLE',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INCOMPLETE_STREAM: 'INCOMPLETE_STREAM',
  INVALID_CONTENT_TYPE: 'INVALID_CONTENT_TYPE',
  INVALID_FILENAME: 'INVALID_FILENAME',
  MAX_SIZE_EXCEEDED: 'MAX_SIZE_EXCEEDED',
  SCAN_ATTEMPTS_EXHAUSTED: 'SCAN_ATTEMPTS_EXHAUSTED',
  SCAN_LEASE_EXPIRED: 'SCAN_LEASE_EXPIRED',
  SCAN_MESSAGE_MISMATCH: 'SCAN_MESSAGE_MISMATCH',
  STORAGE_CONTENT_SHA256_MISMATCH: 'STORAGE_CONTENT_SHA256_MISMATCH',
  STORAGE_CONTENT_SIZE_MISMATCH: 'STORAGE_CONTENT_SIZE_MISMATCH',
  STORAGE_INTEGRITY_MISMATCH: 'STORAGE_INTEGRITY_MISMATCH',
  STORAGE_OBJECT_NOT_FOUND: 'STORAGE_OBJECT_NOT_FOUND',
  STORAGE_SIZE_MISMATCH: 'STORAGE_SIZE_MISMATCH',
  STORAGE_VERSION_MISMATCH: 'STORAGE_VERSION_MISMATCH',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  UPLOAD_READ_FAILED: 'UPLOAD_READ_FAILED',
} as const;

const failureDescriptions: Record<string, string> = {
  [FILE_FAILURE_CODES.ANTIVIRUS_UNAVAILABLE]: 'Service antivirus indisponible',
  [FILE_FAILURE_CODES.CLAMAV_INVALID_RESPONSE]: 'Réponse du service antivirus invalide',
  [FILE_FAILURE_CODES.CLAMAV_UNAVAILABLE]: 'Service antivirus indisponible',
  [FILE_FAILURE_CODES.CONTENT_UNAVAILABLE]: 'Contenu du fichier indisponible',
  [FILE_FAILURE_CODES.DECLARED_SIZE_MISMATCH]: 'Taille déclarée incohérente',
  [FILE_FAILURE_CODES.FILE_NOT_AVAILABLE]: 'Fichier non disponible',
  [FILE_FAILURE_CODES.FILE_NOT_FOUND]: 'Fichier introuvable',
  [FILE_FAILURE_CODES.INCOMPLETE_STREAM]: 'Transmission incomplète',
  [FILE_FAILURE_CODES.INVALID_CONTENT_TYPE]: 'Type de contenu invalide',
  [FILE_FAILURE_CODES.INVALID_FILENAME]: 'Nom de fichier invalide',
  [FILE_FAILURE_CODES.MAX_SIZE_EXCEEDED]: 'Taille maximale dépassée',
  [FILE_FAILURE_CODES.SCAN_ATTEMPTS_EXHAUSTED]: 'Nombre maximal de tentatives atteint',
  [FILE_FAILURE_CODES.SCAN_LEASE_EXPIRED]: 'Analyse interrompue',
  [FILE_FAILURE_CODES.SCAN_MESSAGE_MISMATCH]: 'Métadonnées de scan incohérentes',
  [FILE_FAILURE_CODES.STORAGE_CONTENT_SHA256_MISMATCH]: 'Empreinte du contenu incohérente',
  [FILE_FAILURE_CODES.STORAGE_CONTENT_SIZE_MISMATCH]: 'Taille du contenu incohérente',
  [FILE_FAILURE_CODES.STORAGE_INTEGRITY_MISMATCH]: 'Intégrité du fichier non vérifiable',
  [FILE_FAILURE_CODES.STORAGE_OBJECT_NOT_FOUND]: 'Objet de stockage introuvable',
  [FILE_FAILURE_CODES.STORAGE_SIZE_MISMATCH]: 'Taille du fichier incohérente',
  [FILE_FAILURE_CODES.STORAGE_VERSION_MISMATCH]: 'Version du fichier incohérente',
  [FILE_FAILURE_CODES.UPLOAD_FAILED]: 'Échec de l\'upload',
  [FILE_FAILURE_CODES.UPLOAD_READ_FAILED]: 'Lecture du fichier impossible',
};

export function fileFailureDetails(failureCode: string | null | undefined) {
  if (!failureCode) {
    return undefined;
  }
  const description = failureDescriptions[failureCode] ?? 'Erreur de traitement du fichier';
  return `${description} (${failureCode})`;
}